version: '3.8'

networks:
    webapp:
services:

    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8099:8099"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
        depends_on:
            - app
            - db
        networks:
            - webapp

    db:
        image: postgres
        container_name: postgres
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: office
            POSTGRES_USER: dimas
            POSTGRES_PASSWORD: dimas1950
        networks:
            - webapp

    app:
        container_name: office
        args:
            - UID=${uid:-www-data}
            - GID=${gid:-www-data}
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        working_dir: /var/www/html
        networks:
            - webapp

    #phpMyAdmin Service
    # phpmyadmin:
    #   image: phpmyadmin/phpmyadmin
    #   container_name: phpmyadmin
    #   ports:
    #     - "3400:80"
    #   depends_on:
    #     - db


    # pgadmin:
    #     image: dpage/pgadmin4
    #     container_name: pgAdmin
    #     ports:
    #         - "5050:80"
    #     depends_on:
    #         - db
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: hanieasemi76@gmail.com
    #         PGADMIN_DEFAULT_PASSWORD: password
