version: '3.8'

networks:
    office:


services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx_office
        ports:
            - "8099:8099"
        links:
            -php
        volumes:
            - ./:/var/html
            - .docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - .docker/logs/nginx:/var/logs/nginx:rw
        networks:
            - office
        depends_on:
            - php
            - postgres

    php:
        build:
            context: .
            dockerfile: dockerfile
        container_name: php_office
        volumes:
            - ./:/var/www/html
        ports:
            - "9001:9000"
        networks:
            - office
    postgres:
        image: postgres
        container_name: postgres_office
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER: dimas
            - POSTGRES_PASSWORD: dimas1950
            - POSTGRES_DB: office
            - POSTGRES_HOST_AUTH_METHOD: "trust"
        networks:
            - office
